### ISSUE TITLE
Error: This value of type "String" has no property named "description".

### ISSUE THREAD

**Issue by megabugman** [maessof91/Ahk2Commands#1]
clicked once in the GUI:
![image](https://github.com/user-attachments/assets/37b27f56-bbd0-4edd-a04f-46c69bf6081d)

**Comment by maessof91** [comment]
Ill have a look,  Thanks

**Comment by maessof91** [comment]
Fixed, I tend to use the other branch, so master was missing the loading of the list of commands at startup.
On your version if you type a character and then remove it, should see the default list of commands.
Or download latest.
Double clicking an empty command still results in that error
